### Carga de la biblioteca numpy

In [2]:
import numpy  # Importamos NumPy
numpy.__version__

'2.4.1'

### Instalación de numpy en caso de no tenerlo

In [4]:
# Instalación, en caso de que falle lo de arriba
%pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


### Carga de la biblioteca NumPy con un alias


In [3]:
# Importamos NumPy y usamos el alias np para llamarlo de manera más corta
import numpy as np
np.__version__

'2.4.1'

### Ayuda o documentación de NumPy

In [ ]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [6]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\mag_l\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\mag_l\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets

### Comparación: Listas vs. NumPy

In [1]:
arreglo = np.array([1, 4, 2, 5, 3])
print(arreglo)

NameError: name 'np' is not defined

In [ ]:
# Crear un arreglo a partir de una lista
#arreglo = np.array([10]*10)
arreglo = np.array([1, 4, 2, 5, 3],dtype='int16')
print(arreglo)
for i in arreglo:
    print(type(i))




[1 4 2 5 3]
<class 'numpy.int16'>
<class 'numpy.int16'>
<class 'numpy.int16'>
<class 'numpy.int16'>
<class 'numpy.int16'>


In [ ]:
arreglo = np.array([1, 4, 2.5, 5, 3],dtype='float32')
print(arreglo)
for i in arreglo:
    print(type(i))

[1.  4.  2.5 5.  3. ]
<class 'numpy.float32'>
<class 'numpy.float32'>
<class 'numpy.float32'>
<class 'numpy.float32'>
<class 'numpy.float32'>


In [3]:
arreglo = np.array([[1,0],[0,1]],dtype='float32')
print(arreglo)
print(type(arreglo))
for i in arreglo:
    for j in i:
        print(j,":",type(j))

NameError: name 'np' is not defined

[range(i,i+3) for i in [2,46,100]]      #List comprehension
[range(2,2+3),range(46,46+3),range(100,100+3)]  # Lista de rangos
[range(2,5),range(46,49),range(100,103)]    #Lista de rangos

np.array([range(2,5),range(46,49),range(100,103)])  # devuelve un arreglo

[[2, 3, 4], [46, 47, 48], [100,101,102]]      #Ya es un arreglo

In [8]:
arreglo = np.array([range(i,i+3) for i in [2,46,100]])
print(arreglo)

[[  2   3   4]
 [ 46  47  48]
 [100 101 102]]


In [9]:
arreglo.ndim

2

Funciones predefinidas en NumPy

In [ ]:
arreglo = np.zeros(100,dtype='int')
print(arreglo)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
arreglo = np.ones(100,dtype='long')
print(arreglo)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [10]:
arreglo = np.ones((3,3,3),dtype='int')
print(arreglo)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [11]:
arreglo.ndim

3

In [ ]:
arreglo = np.ones((3,3),dtype='int')
print(arreglo)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
arreglo = np.full((3,3),np.pi)
print(arreglo)

[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]


In [ ]:
arreglo = np.full((3,3),10)
print(arreglo)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
arreglo = np.linspace(0,1,5)
print(arreglo)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arreglo = np.linspace(0,10,11)
print(arreglo)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
arreglo = np.random.randint(0,10,(3,3))
print(arreglo)

[[5 5 7]
 [9 7 8]
 [6 2 2]]


In [ ]:
arreglo = np.random.normal(0,10,(3,3)) #media 0 y desviación estándar 10
print(arreglo)

[[-3.63704249 -6.50777291  0.58837806]
 [-4.48486481 -7.06601072 -6.30561211]
 [-5.40727061 15.98029325 -1.41504743]]


In [ ]:
np.eye(3) #Matriz de 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty(3,dtype='int')

array([          840, 1318789570722, 1320130643616])

### 1. Velocidad y Eficiencia

In [ ]:
import time

# Con listas de Python
lista = list(range(1_000_000))
start_time = time.time()
lista_squared = [x**2 for x in lista]
print("Tiempo con listas:", time.time() - start_time)

# Con NumPy
array = np.arange(1_000_000)
start_time = time.time()
array_squared = array**2
print("Tiempo con NumPy:", time.time() - start_time)


Tiempo con listas: 0.12115240097045898
Tiempo con NumPy: 0.008081674575805664


In [12]:
a1=np.random.randint(10,size=6)
print(a1.ndim)

1


Consistencia en los Tipos de Datos

In [14]:
lista = [1, "hola", 3.14, True]  # Mezcla de tipos en listas

array = np.array([1, 2, 3, 4])  # NumPy convierte todo a un solo tipo (int)
array.dtype

dtype('int32')

Operaciones Matemáticas Vectorizadas

In [15]:
lista = [1, 2, 3, 4]
lista_doble = [x * 2 for x in lista]  # Necesita un bucle

array = np.array([1, 2, 3, 4])
array_doble = array * 2  # Operación directa y más rápida


Funcionalidad Adicional

In [16]:
array = np.array([1, 2, 3, 4])
print("Raíz cuadrada:", np.sqrt(array))
print("Suma acumulada:", np.cumsum(array))
print("Media:", np.mean(array))


Raíz cuadrada: [1.         1.41421356 1.73205081 2.        ]
Suma acumulada: [ 1  3  6 10]
Media: 2.5


Arreglos Multidimensionales

In [27]:
# Crear un array 1D
arr1 = np.array([1, 2, 3, 4])

# Crear una matriz 2D
arr2 = np.array([[1, 2, 3], [4, 5, 6]],dtype='int8')

# Crear un array 3D (cubo de datos)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]],dtype='float32')

print(arr1, "\n\n", arr2, "\n\n", arr3)


[1 2 3 4] 

 [[1 2 3]
 [4 5 6]] 

 [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


Propiedades de los arrays:

In [22]:
print("Forma:", arr1.shape)  # (filas, columnas)
print("Dimensiones:", arr1.ndim)
print("Tamaño total:", arr1.size)
print("Tipo de datos:", arr1.dtype)
print("Itemsize:",arr1.itemsize, "bytes")
print("nbytes:", arr1.nbytes,"bytes")

Forma: (4,)
Dimensiones: 1
Tamaño total: 4
Tipo de datos: int32
Itemsize: 4 bytes
nbytes: 16 bytes


In [25]:
print("Forma:", arr2.shape)  # (filas, columnas)
print("Dimensiones:", arr2.ndim)
print("Tamaño total:", arr2.size)
print("Tipo de datos:", arr2.dtype)
print("Itemsize:",arr2.itemsize, "bytes")
print("nbytes:", arr2.nbytes,"bytes")


Forma: (2, 3)
Dimensiones: 2
Tamaño total: 6
Tipo de datos: int8
Itemsize: 1 bytes
nbytes: 6 bytes


In [28]:
print("Forma:", arr3.shape)  # (filas, columnas)
print("Dimensiones:", arr3.ndim)
print("Tamaño total:", arr3.size)
print("Tipo de datos:", arr3.dtype)
print("Itemsize:",arr3.itemsize, "bytes")
print("nbytes:", arr3.nbytes,"bytes")

Forma: (2, 2, 2)
Dimensiones: 3
Tamaño total: 8
Tipo de datos: float32
Itemsize: 4 bytes
nbytes: 32 bytes


Operaciones aritméticas con arrays:

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Suma:", a + b)
print("Resta:", a - b)
print("Multiplicación:", a * b)
print("División:", a / b)
print("Potencia:", a**2)


Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]
Potencia: [1 4 9]


Funciones matemáticas comunes:

In [30]:
x = np.array([0, np.pi / 2, np.pi])

print("Seno:", np.sin(x))
print("Coseno:", np.cos(x))
print("Raíz cuadrada:", np.sqrt([4, 9, 16]))
print("Logaritmo:", np.log([1, np.e, np.e**2]))


Seno: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Coseno: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Raíz cuadrada: [2. 3. 4.]
Logaritmo: [0. 1. 2.]


Caso práctico: Generar datos de salarios de 100 empleados con distribución normal:

In [32]:
salarios = np.random.normal(loc=50000, scale=10000, size=100)
print("Salario promedio:", np.mean(salarios))
print("Desviación estándar:", np.std(salarios))


Salario promedio: 48939.47427914615
Desviación estándar: 10660.494642610347
