# Ejercicio 1:

 Crea el siguiente arreglo a partir de una lista con np.array().

In [43]:
import pandas as pd
#importando libreria
import numpy as np

In [ ]:
array = np.array([[[1,2,3,4],
           [5,6,7,8]],

           [[9,10,11,12],
           [13,14,15,16]],

           [[17,18,19,20],
           [21,22,23,24]]])


#1. imprimiento el tercer subarreglo (17,18,19,20,21,22,23,24).
array[2]


np.int64(24)

In [17]:

#2. Último elemento (24).
array[2][1][3]

np.int64(24)

In [21]:
#3. Elementos de la segunda columna (2,6,10,14,18,22).
array[:,:,1]

array([[ 2,  6],
       [10, 14],
       [18, 22]])

In [37]:
# 4. Los siguientes elementos: 1,10,19,24.

print(array[0,0,0])
print(array[1,0,1])
print(array[2,0,2])
print(array[2,1,3])

1
10
19
24


# Ejercicio 2:

 En clase exploramos diversas funciones predefinidas de NumPy para generar
arreglos, tales como: np.zeros, np.ones, np.full, np.arange, np.linspace,
np.random.random, np.random.normal, np.random.randint, np.eye y np.empty.

In [ ]:
#importando libreria
import random

for i in range (7):
# Un arreglo con siete números aleatorios.
    numero_aleatorio = np.random.randint(1,1000)
    print(f"Número aleatorio: {numero_aleatorio}")

    


Número aleatorio: 371
Número aleatorio: 644
Número aleatorio: 398
Número aleatorio: 583
Número aleatorio: 65
Número aleatorio: 911
Número aleatorio: 198


In [ ]:
# 2. Un arreglo no inicializado de 2 filas y 5 columnas (2 × 5).  REVISAR ESTEEEEEEE!!!!!!
array2 = np.empty([2,5])
print(array2)

[[6.91691904e-323 9.69483728e-315 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  1.11253693e-308]]


In [11]:
# 3. Un arreglo con diez números de coma flotante igualmente espaciados entre 1 y 3

array3 = np.linspace(1,3,10)
print(array3)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [14]:
# 4. Un arreglo de 3 × 3 con todos los valores como 100
array4 = np.full((3,3), 100)
print(array4)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


# Ejercicio 3:
 Escribe instrucciones de código sencillas para cada uno de los siguientes
casos:

In [ ]:
# 1. Crea un arreglo para almacenar los 50 primeros números pares.
array5 = np.arange(2,102,2)
print(array5)

conteo = len(array5)
print(f"El número de números pares es: {conteo}") #para comprobar que sí eran 50 

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
El número de números pares es: 50


In [ ]:
# 2. Calcula la media y la desviación estándar de estos números.

media = np.mean(array5)


In [17]:
# 2. Calcula la media y la desviación estándar de estos números.
desviacion_estandar = np.std(array5)
print(desviacion_estandar)

28.861739379323623


In [28]:
#3. Convierte este arreglo en un arreglo con dos subarreglos, cada una con cinco filas y cinco columnas (25 datos en subarreglo y 25 datos en otro).
convertir_arreglo = array5.reshape(2, 5, 5)
print(convertir_arreglo)

[[[  2   4   6   8  10]
  [ 12  14  16  18  20]
  [ 22  24  26  28  30]
  [ 32  34  36  38  40]
  [ 42  44  46  48  50]]

 [[ 52  54  56  58  60]
  [ 62  64  66  68  70]
  [ 72  74  76  78  80]
  [ 82  84  86  88  90]
  [ 92  94  96  98 100]]]


In [35]:
# 4. Calcular las dimensiones de este arreglo reformado.
dimensiones = convertir_arreglo.shape
print(dimensiones)

(2, 5, 5)


# Ejercicio 4:
 Producto punto en NumPy

In [40]:
# declarando el arreglo:

A = np.array([
    [2, 3],
    [33 ,3],
    [4, 1]
])

B = np.array([
    [2, 3, 33],
    [3, 4, 1]
])


# Usa Numpy para calcular el producto C = A @ B  Ó   C = np.dot(A,B)
C = A @ B
print(f"El resultado es: {C}")

El resultado es: [[  13   18   69]
 [  75  111 1092]
 [  11   16  133]]


### Reflexiona: ¿por qué la matriz resultante tiene esas dimensiones?

RESPUESTA: 
Porque cuando se hace una multiplicación de matrices, se hace fila por columna, y como en este caso es de 2 x 3, pues queda por eso de esa dimensión




### ¿Cómo se relaciona con los datos originales?
No se si estoy entendiendo la pregunta, pero asumo que me pregunta por qué da como resultado la matriz.
Los elementos de la matriz resultante salen de multiplicar las filas de la matriz A con las columnas de la matriz B 


### 4. Modifica las dimensiones de la matriz B para que sea de 3 × 3 e intenta correr el código de nuevo.

In [41]:
# modificando las dimensiones internas de las matrices

A = np.array([
    [2, 3],
    [33 ,3],
    [4, 1]
])

B = np.array([
    [2, 3, 33],
    [3, 4, 1],
    [1, 1 ,1]
])


# Usa Numpy para calcular el producto C = A @ B  Ó   C = np.dot(A,B)
C = A @ B
print(f"El resultado es: {C}")


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

¿Qué error te arroja Python?
 Explica con tus propias palabras por
qué las dimensiones internas de las matrices deben coincidir para que el producto
punto sea válido.

RESPUESTA: 
sale un error de que no se puede efectuar la operación de matrices, y esto pasa porque como las operaciones se efectúan como: fila x columna, en un punto, faltaría otra fila en A 
para que se pudieran hacer de manera correcta las operaciones. Para que se pudiera efectuar la operación, sus dimensiones tienen que ser iguales.

# Ejercicio 5:
 Diferencia entre listas y arrays en operaciones

In [ ]:
# array 
import numpy as np
x = np.array([1, 2, 3])
x * 3

array([3, 6, 9])

In [46]:
# Usando listas de python 
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

Preguntas:
1. ¿Cuál es la diferencia entre los resultados de x * 3 y a * 3?
Con el array solamente multiplica a cada elemento de este por 2 mientras que en la lista repite los elementos de a 3 veces en la lista


2. ¿Por qué ocurre esta diferencia?
Ocurre porque los arrays permiten efectuar operaciones vectorizadas, mientras que una lista no deja hacer operaciones de manera directa, por eso sólo nos repite los elementos de a 3 veces.


3. ¿Cómo podrías modificar el código en la Parte 2 para obtener un comportamiento
similar al de Parte 1 sin transformar la lista en un arreglo?
Pista: En NumPy, los arrays permiten realizar operaciones matemáticas directamente,
mientras que las listas en Python tienen un comportamiento diferente al usar el operador *.

## Lo único que se me ocurrió fue recorrer la lista con un for y hacer que multiplique elemento por elemento... 

In [ ]:
#modificando la parte 2: 
a = [1, 2, 3]
resultado = [] #los guarda aquí
contador = 0
for i in a: # recorre "a"
    multiplicacion = i * 3
    resultado.append(multiplicacion) #agrega los números multiplicados en el arreglo
print(resultado)


[3, 6, 9]


# Ejercicio 6: 
Explorando los tipos de datos en NumPy

In [54]:
# Ejecuta el siguiente código y observa los resultados:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1.5, 2.5, 3.5])
arr3 = np.array([True, False, True])
arr4 = np.array(["Hola", "Numpy", "Python"])


print(arr1.dtype)

print(arr2.dtype)

print(arr3.dtype)

print(arr4.dtype)

int64
float64
bool
<U6


# # 1. ¿Qué tipos de datos muestra NumPy para cada caso?



1- para el primero es un entero

2- para el segundo se un dato del tipo flotante

3- para el tercero es un tipo boleano  

4- para el cuarto me dice que es un arreglo de cadenas (string) con una longitud máxima de 6



In [63]:
# Parte 2: Cambia el tipo de datos
arr1_boolean = np.array([1 , 2, 3,], dtype = np.bool) # convierte el entero en boolean
arr2_int = np.array([1.5, 2.5, 3.5], dtype = np.int64) # convierte float en int
arr3_float = np.array([True, False, True], dtype = np.float32) # convierte boolean en float
arr4_boolean_again = np.array(["Hola", "Numpy", "Python"], dtype = bool) # convierte cadena a int

print(arr1_boolean.dtype)
print(arr2_int.dtype)
print(arr3_float)
print(arr4_boolean_again)


bool
int64
[1. 0. 1.]
[ True  True  True]
