# Ejercicio 1:

 Crea el siguiente arreglo a partir de una lista con np.array().

In [16]:
#importando libreria
import numpy as np

In [ ]:
array = np.array([[[1,2,3,4],
           [5,6,7,8]],

           [[9,10,11,12],
           [13,14,15,16]],

           [[17,18,19,20],
           [21,22,23,24]]])


#1. imprimiento el tercer subarreglo (17,18,19,20,21,22,23,24).
array[2]


np.int64(24)

In [17]:

#2. Último elemento (24).
array[2][1][3]

np.int64(24)

In [21]:
#3. Elementos de la segunda columna (2,6,10,14,18,22).
array[:,:,1]

array([[ 2,  6],
       [10, 14],
       [18, 22]])

In [37]:
# 4. Los siguientes elementos: 1,10,19,24.

print(array[0,0,0])
print(array[1,0,1])
print(array[2,0,2])
print(array[2,1,3])

1
10
19
24


# Ejercicio 2:

 En clase exploramos diversas funciones predefinidas de NumPy para generar
arreglos, tales como: np.zeros, np.ones, np.full, np.arange, np.linspace,
np.random.random, np.random.normal, np.random.randint, np.eye y np.empty.

In [ ]:
#importando libreria
import random

for i in range (7):
# Un arreglo con siete números aleatorios.
    numero_aleatorio = np.random.randint(1,1000)
    print(f"Número aleatorio: {numero_aleatorio}")

    


Número aleatorio: 371
Número aleatorio: 644
Número aleatorio: 398
Número aleatorio: 583
Número aleatorio: 65
Número aleatorio: 911
Número aleatorio: 198


In [ ]:
# 2. Un arreglo no inicializado de 2 filas y 5 columnas (2 × 5).  REVISAR ESTEEEEEEE!!!!!!
array2 = np.empty([2,5])
print(array2)

[[6.91691904e-323 9.69483728e-315 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  1.11253693e-308]]


In [11]:
# 3. Un arreglo con diez números de coma flotante igualmente espaciados entre 1 y 3

array3 = np.linspace(1,3,10)
print(array3)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [14]:
# 4. Un arreglo de 3 × 3 con todos los valores como 100
array4 = np.full((3,3), 100)
print(array4)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


# Ejercicio 3:
 Escribe instrucciones de código sencillas para cada uno de los siguientes
casos:

In [ ]:
# 1. Crea un arreglo para almacenar los 50 primeros números pares.
array5 = np.arange(2,102,2)
print(array5)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
